### PR TITLE
Added Fullscreen feature (Work in Progress)

### PR DESCRIPTION
**Pull request by AlexErling**
So I was able to create the buttons to be able to toggle full screen and escape it, as well as make 0 the request a new game button. However, when I go full screen it doesn't respond to it and I was wondering if you might be able to look at what I have and see what I might need to fix it.

### CODE REVIEW

**Comment by AlexErling** [comment]
So I noticed that if I click F11, and it goes full screen, then I click out of the window and then back on it it will make the adjustment to full screen. I don't know what it's not automatically doing it though.

**Comment by nikolockenvitz** [comment]
I would suggest to use `self.root.state("zoomed")` instead of `self.root.attributes("-fullscreen, True)`. Then it should work I think.

**Comment by AlexErling** [comment]
Okay, I made that change. However with this function
```
    def toggle_fullscreen(self, event=None):
        self.root.state("zoomed")
```
When its clicked, it'll begin to get bigger than the window will shrink back to normal size. I think something in the setWindowSize is causing it to shrink back down. Any thoughts?

**Comment by nikolockenvitz** [comment]
I uploaded some changes in https://github.com/nikolockenvitz/2048/tree/feature/%237. This works on my machine ;) Does it work for you?

**Pull request closed without merging**
